language: python
sudo: required
dist: xenial
branches:
  only:
    master
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install --upgrade pip
  # - pip install -r requirements.txt
  - pip install numpy
  - pip install pandas
  - pip install h5py
  - pip install numba
  - pip install tqdm
  - pip install isochrones
  # install packages for documentation building
  # - pip install sphinx sphinx-rtd-theme
  # install packages for testing
  - pip install --upgrade pytest>=3.6.3
  # build stardate
  - pip install -e .
script:
  # run the test script
  - pytest
  # try building documentation
  # - cd docs
  # - mkdir source/_static
  # - make html
  # return to base directory
  # - cd ..
# after_success:
#   - codecov
